ALTER USER postgres WITH PASSWORD 'lernvo';
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'lernvo') THEN
    CREATE ROLE lernvo LOGIN PASSWORD 'lernvo' SUPERUSER CREATEDB;
  ELSE
    ALTER ROLE lernvo WITH LOGIN PASSWORD 'lernvo' SUPERUSER CREATEDB;
  END IF;
END $$;
